### ISSUE TITLE
Uptime monitoring / cronjob monitoring

### ISSUE THREAD

**Issue by tillprochaska** [ep-votes/epvotes#216]
* Create a central email address for alerts (e.g. alerts@host) that forwards any emails to our personal email addresses
* Set up a monitoring service for cronjobs (e.g. ohmydear.app)
* Ping the monitoring service every time a job runs ([Laravel docs](https://laravel.com/docs/8.x/scheduling#pinging-urls)).

**Comment by linusha** [comment]
Closed by #235.
