### ISSUE TITLE
Local changes on server cause Ansible playbook to fail

### ISSUE THREAD

**Issue by tillprochaska** [ep-votes/epvotes#227]
In case of local changes, cloning/updating the git repository fails due to uncommitted changes. Steps to reproduce:

* Change a tracked file on the target server
* Run the Ansible playbook

**Comment by linusha** [comment]
Führt das dazu, dass sobald Bilder ertellt werden das Deployment failed? Bzw selbst wenn nicht, sollten wir nochmal sicherstellen, dass die Bilder erhalten bleiben.

**Comment by tillprochaska** [comment]
> Führt das dazu, dass sobald Bilder ertellt werden das Deployment failed?

Ne, weil Storage ignoriert wird.
